### ISSUE TITLE
Espresso 0.7.0 groupby sex compareby status or vice versa not working

### ISSUE THREAD

**Issue by sangyu** [josesho/ESPRESSO#41]
if I do the following: 

```python
groupby='Status'
compareby='Sex'

volume = MS48.plot.contrast.feed_volume_per_fly(group_by=groupby, 
                                                       compare_by=compareby,start_hour=0,
                                                     end_hour=2)

fvolume = volume.mean_diff.plot(color_col='Genotype')

```

the same output happens, which is wrongly grouped.
.flies and .feeds dataframes appear to be correctly labeled. 

![groupbyStatusComparebySex](https://user-images.githubusercontent.com/3475341/56644041-7fbd5280-66ad-11e9-881b-648326d464c1.png)

esp object attached here. 

[MS48.espresso.zip](https://github.com/ACCLAB/espresso/files/3111289/MS48.espresso.zip)

**Comment by josesho** [comment]
Oh dear. I will take a look at this and get back to you!

**Comment by josesho** [comment]
Can you pass me the raw data? 

The espresso object you sent me was created in v0.6.0; I suspect you need to re-create the object (from the raw data) in v0.7.0.

**Comment by sangyu** [comment]
https://drive.google.com/file/d/1mDPyV7JYMnRVttEp1RPDE0VfYrKfN8LP/view?usp=sharing
but i don't even have espresso v0.6.0...
![Screen Shot 2019-04-25 at 3 08 41 PM](https://user-images.githubusercontent.com/3475341/56716093-0173b580-676c-11e9-8bf6-99f00f254809.png)

**Comment by josesho** [comment]
Right, but the `MS48.espresso` file you first sent was created with espresso v0.6.0. And I can't seem tp unzip the second zip file... :(

when you are back at your desk, let me come over and copy it off a thumb drive....
![Screen Shot 2019-04-25 at 16 10 31](https://user-images.githubusercontent.com/12838917/56720255-09842300-6775-11e9-96a8-0942af9a3cc2.png)

**Comment by sangyu** [comment]
Also, while you are looking at this:
1. do you know why Genotype can no longer be used to group by or compare by?
2. y-axis labels are not there any more? can I add them posthoc? 
Muchas gracias!

**Comment by josesho** [comment]
Hi @sangyu 

Here's a dirty hack-around for this issue:

1. Load your data.
```python
my_data = esp.espresso(directory_with_data, expt_duration_minutes=120)
```

2. Grab the data for plotting. (Note the `.data` property at the end!)
```python
for_plot = my_data.plot.contrast.feed_count_per_fly(group_by="Status", 
                                                    compare_by="FoodChoice").data
```

3. The plot groups are in the column `plot_groups_with_contrast`.  It is a pandas Categorical object, which gums up the plotting, for an as yet unknown reason. So, we turn it into a string object instead.

```python
for_plot.loc[:, "plot_groups_with_contrast"] = for_plot.plot_groups_with_contrast.astype(str)
```

4. Set up the groups you want to compare.
```python
for_plot.plot_groups_with_contrast.unique()
```

which returns this
```shell
array(['Sibling; 100mM_Sucrose', 'Sibling; 100mM_Sucrose_100mM_Arabinose',
       'Offspring; 100mM_Sucrose',
       'Offspring; 100mM_Sucrose_100mM_Arabinose'], dtype=object)
```

Using this, create your `idx`. (Sorry this bit is a little manual.)
```python

idx1 = [('Sibling; 100mM_Sucrose', 'Sibling; 100mM_Sucrose_100mM_Arabinose'),
           ('Offspring; 100mM_Sucrose', 'Offspring; 100mM_Sucrose_100mM_Arabinose')]
```

5.. Load this dataframe into dabest, along with the correct x and y columns below. (If you want to plot other metrics, let me know.)

```python
dabest_settings = dict('x': 'plot_groups_with_contrast', 
                       'y': 'Total\nFeed Volume\nPer Fly (µl)')

db1 = dabest.load(for_plot, idx=idx1, **dabest_settings)
# Use the y column in `dabest_settings as the swarm label!
db1.mean_diff.plot(swarm_label=dabest_settings['y']);
```

6. To change the plot order, change the idx and reload the dataframe into dabest.
```python
idx2 = [('Sibling; 100mM_Sucrose', 'Offspring; 100mM_Sucrose'),
         ('Sibling; 100mM_Sucrose_100mM_Arabinose', 'Offspring; 100mM_Sucrose_100mM_Arabinose')]

db2 = dabest.load(for_plot, idx=idx2, **dabest_settings)
db2.mean_diff.plot(swarm_label=dabest_settings['y']);
```

**Comment by josesho** [comment]
Genotype by default is set as `color_by`. You will need to set this to some other value (eg Sex or Temperature) so you can `group_by` or `compare_by` Genotype!

> 1. do you know why Genotype can no longer be used to group by or compare by?

**Comment by josesho** [comment]
I think I've fixed this! See screenshot for demo below. Update your local repo and install as per normal.

![image](https://user-images.githubusercontent.com/12838917/57209375-0279d200-700b-11e9-9b71-37c249570037.png)

**Comment by sangyu** [comment]
awesome! i try now
